package br.com.controlextras.tela;

import java.awt.event.KeyEvent;

public class TelaMain extends javax.swing.JDialog {


    
    public TelaMain(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        configTela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        pnlFuncionario = new javax.swing.JPanel();
        btnPainelHoraExtras = new javax.swing.JButton();
        btnInscreverHoraExtra = new javax.swing.JButton();
        btnAlteraSenha = new javax.swing.JButton();
        pnlGerente = new javax.swing.JPanel();
        btnCadastroFuncionario = new javax.swing.JButton();
        pnlCoordenador = new javax.swing.JPanel();
        btnRelatorioHoraExtra = new javax.swing.JButton();
        btnAprovarHoraExtra = new javax.swing.JButton();
        btnCadastoHoraExtra = new javax.swing.JButton();
        lblBoasVinda = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Sistema de Hora Extras");
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(23, 24, 31));
        jPanel2.setForeground(new java.awt.Color(23, 24, 31));

        pnlFuncionario.setBackground(new java.awt.Color(23, 24, 31));
        pnlFuncionario.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 2), "Funcionário", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 18), new java.awt.Color(11, 135, 112))); // NOI18N

        btnPainelHoraExtras.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnPainelHoraExtras.setMnemonic(KeyEvent.VK_M);
        btnPainelHoraExtras.setText("Minhas Horas Extras");
        btnPainelHoraExtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPainelHoraExtrasActionPerformed(evt);
            }
        });

        btnInscreverHoraExtra.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnInscreverHoraExtra.setMnemonic(KeyEvent.VK_I);
        btnInscreverHoraExtra.setText("Inscrever-se em Hora Extra");
        btnInscreverHoraExtra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInscreverHoraExtraActionPerformed(evt);
            }
        });

        btnAlteraSenha.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAlteraSenha.setMnemonic(KeyEvent.VK_S);
        btnAlteraSenha.setText("Alterar Senha");
        btnAlteraSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlteraSenhaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlFuncionarioLayout = new javax.swing.GroupLayout(pnlFuncionario);
        pnlFuncionario.setLayout(pnlFuncionarioLayout);
        pnlFuncionarioLayout.setHorizontalGroup(
            pnlFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFuncionarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnPainelHoraExtras)
                .addGap(18, 18, 18)
                .addComponent(btnInscreverHoraExtra)
                .addGap(18, 18, 18)
                .addComponent(btnAlteraSenha)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlFuncionarioLayout.setVerticalGroup(
            pnlFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFuncionarioLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(pnlFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPainelHoraExtras)
                    .addComponent(btnInscreverHoraExtra)
                    .addComponent(btnAlteraSenha))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pnlGerente.setBackground(new java.awt.Color(23, 24, 31));
        pnlGerente.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 2), "Gerente", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 18), new java.awt.Color(11, 135, 112))); // NOI18N

        btnCadastroFuncionario.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCadastroFuncionario.setMnemonic(KeyEvent.VK_F);
        btnCadastroFuncionario.setText("Cadastro de Funcionários");
        btnCadastroFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastroFuncionarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlGerenteLayout = new javax.swing.GroupLayout(pnlGerente);
        pnlGerente.setLayout(pnlGerenteLayout);
        pnlGerenteLayout.setHorizontalGroup(
            pnlGerenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlGerenteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnCadastroFuncionario)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlGerenteLayout.setVerticalGroup(
            pnlGerenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlGerenteLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(btnCadastroFuncionario)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        pnlCoordenador.setBackground(new java.awt.Color(23, 24, 31));
        pnlCoordenador.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 2), "Coordenador", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 18), new java.awt.Color(11, 135, 112))); // NOI18N

        btnRelatorioHoraExtra.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnRelatorioHoraExtra.setMnemonic(KeyEvent.VK_R);
        btnRelatorioHoraExtra.setText("Relatório de Hora Extra");
        btnRelatorioHoraExtra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRelatorioHoraExtraActionPerformed(evt);
            }
        });

        btnAprovarHoraExtra.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAprovarHoraExtra.setMnemonic(KeyEvent.VK_A);
        btnAprovarHoraExtra.setText("Aprovar Hora Extra");
        btnAprovarHoraExtra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAprovarHoraExtraActionPerformed(evt);
            }
        });

        btnCadastoHoraExtra.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCadastoHoraExtra.setMnemonic(KeyEvent.VK_C);
        btnCadastoHoraExtra.setText("Cadastro de Hora Extra");
        btnCadastoHoraExtra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastoHoraExtraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlCoordenadorLayout = new javax.swing.GroupLayout(pnlCoordenador);
        pnlCoordenador.setLayout(pnlCoordenadorLayout);
        pnlCoordenadorLayout.setHorizontalGroup(
            pnlCoordenadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCoordenadorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnCadastoHoraExtra)
                .addGap(18, 18, 18)
                .addComponent(btnAprovarHoraExtra)
                .addGap(18, 18, 18)
                .addComponent(btnRelatorioHoraExtra)
                .addContainerGap(147, Short.MAX_VALUE))
        );
        pnlCoordenadorLayout.setVerticalGroup(
            pnlCoordenadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCoordenadorLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(pnlCoordenadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRelatorioHoraExtra)
                    .addComponent(btnAprovarHoraExtra)
                    .addComponent(btnCadastoHoraExtra))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        lblBoasVinda.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblBoasVinda.setForeground(new java.awt.Color(11, 135, 112));
        lblBoasVinda.setText("Seja bem vindo, <<user>>");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblBoasVinda))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pnlFuncionario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pnlGerente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pnlCoordenador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lblBoasVinda)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnlFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlCoordenador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlGerente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(245, 245, 245))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 505, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastroFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastroFuncionarioActionPerformed
        // TODO add your handling code here:
        TelaCadFuncionario cad = new TelaCadFuncionario(null, true);
        cad.setVisible(true);
    }//GEN-LAST:event_btnCadastroFuncionarioActionPerformed

    private void btnCadastoHoraExtraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastoHoraExtraActionPerformed
        // TODO add your handling code here:
        TelaCadHoraExtra cad = new TelaCadHoraExtra(null, true);
        cad.setVisible(true);
    }//GEN-LAST:event_btnCadastoHoraExtraActionPerformed

    private void btnInscreverHoraExtraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInscreverHoraExtraActionPerformed
        // TODO add your handling code here: 
        TelaInscHoraExtra telaInscHoraExtra = new TelaInscHoraExtra(null, true);
        telaInscHoraExtra.setVisible(true);
    }//GEN-LAST:event_btnInscreverHoraExtraActionPerformed

    private void btnPainelHoraExtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPainelHoraExtrasActionPerformed
        // TODO add your handling code here:
        TelaHoraExtrasInscrito telaHoraExtrasInscrito = new TelaHoraExtrasInscrito(null, true);
        telaHoraExtrasInscrito.setVisible(true);
    }//GEN-LAST:event_btnPainelHoraExtrasActionPerformed

    private void btnAprovarHoraExtraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAprovarHoraExtraActionPerformed
        // TODO add your handling code here:
        TelaAproHoraExtra telaAproHoraExtra = new TelaAproHoraExtra(null, true);
        telaAproHoraExtra.setVisible(true);
    }//GEN-LAST:event_btnAprovarHoraExtraActionPerformed

    private void btnRelatorioHoraExtraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRelatorioHoraExtraActionPerformed
        // TODO add your handling code here:
        TelaRelatorioHoraExtra telaRelatorioHoraExtra = new TelaRelatorioHoraExtra(null, true);
        telaRelatorioHoraExtra.setVisible(true);
    }//GEN-LAST:event_btnRelatorioHoraExtraActionPerformed

    private void btnAlteraSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlteraSenhaActionPerformed
        // TODO add your handling code here:
        TelaAlterarSenha telaAlterarSenha = new TelaAlterarSenha(null, true);
        telaAlterarSenha.setVisible(true);
    }//GEN-LAST:event_btnAlteraSenhaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(() -> {
            TelaMain dialog = new TelaMain(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlteraSenha;
    private javax.swing.JButton btnAprovarHoraExtra;
    private javax.swing.JButton btnCadastoHoraExtra;
    private javax.swing.JButton btnCadastroFuncionario;
    private javax.swing.JButton btnInscreverHoraExtra;
    private javax.swing.JButton btnPainelHoraExtras;
    private javax.swing.JButton btnRelatorioHoraExtra;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblBoasVinda;
    private javax.swing.JPanel pnlCoordenador;
    private javax.swing.JPanel pnlFuncionario;
    private javax.swing.JPanel pnlGerente;
    // End of variables declaration//GEN-END:variables
        
    private void configTela() {
        lblBoasVinda.setText("Seja bem vindo, " + TelaInicial.funcionario.getNome());
       
        switch (TelaInicial.funcionario.getCargo().getId()) {
            case 3:
                //Cargo 3 = Gerente
                if(!TelaInicial.funcionario.isAtivo()){
                    btnInscreverHoraExtra.setEnabled(false);
                    
                    btnCadastoHoraExtra.setEnabled(false);
                    btnAprovarHoraExtra.setEnabled(false);
                    btnRelatorioHoraExtra.setEnabled(false);
                    
                    btnCadastroFuncionario.setEnabled(false);
                }
                break;
            case 2:
                //Cargo 2 = Coordenador
                if(!TelaInicial.funcionario.isAtivo()){
                    btnInscreverHoraExtra.setEnabled(false);
                    
                    btnCadastoHoraExtra.setEnabled(false);
                    btnAprovarHoraExtra.setEnabled(false);
                    btnRelatorioHoraExtra.setEnabled(false);
                    
                }
                btnCadastroFuncionario.setVisible(false);
                pnlGerente.setVisible(false);
                break;
            case 1:
                //Cargo 1 = Nenhum
                if(!TelaInicial.funcionario.isAtivo()){
                    btnInscreverHoraExtra.setEnabled(false); 
                }
                btnCadastroFuncionario.setVisible(false);
                btnRelatorioHoraExtra.setVisible(false);
                btnCadastoHoraExtra.setVisible(false);
                btnAprovarHoraExtra.setVisible(false);
                pnlGerente.setVisible(false);
                pnlCoordenador.setVisible(false);
                break;
            default:
                break;
        }
    
    }
}
