/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package br.com.controlextras.tela;

import br.com.controlextras.data.FuncionarioDAO;
import br.com.controlextras.modelo.Funcionario;
import java.util.Map;
import javax.swing.JOptionPane;

/**
 *
 * @author Aislan Penha
 */
public class TelaAlterarSenha extends javax.swing.JDialog {

    private boolean emptyFields() {
        boolean resp = false;
        if(pswNovaSenha.getPassword().length == 0){
            JOptionPane.showMessageDialog(null, "Campo Nova Senha está vazio.", "Campo vazio", JOptionPane.WARNING_MESSAGE);
            
            resp = true;
            pswNovaSenha.setText("");
            pswNovaSenha.requestFocus();
        } else if(!java.util.Arrays.equals(pswNovaSenha.getPassword(), pswConfirmeSenha.getPassword())){
            JOptionPane.showMessageDialog(null, "Campo Nova Senha e Confirme senha tem que ser igual.", "Campos diferentes", JOptionPane.WARNING_MESSAGE);
            resp = true;
            pswConfirmeSenha.setText("");
            pswConfirmeSenha.requestFocus();
        }
        return resp;
    }
    public TelaAlterarSenha(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        inseriCpf();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlContainer = new javax.swing.JPanel();
        lblAlterarSenha = new javax.swing.JLabel();
        lblNovaSenha = new javax.swing.JLabel();
        pswNovaSenha = new javax.swing.JPasswordField();
        lblConfirmeSenha = new javax.swing.JLabel();
        pswConfirmeSenha = new javax.swing.JPasswordField();
        btnCancelar = new javax.swing.JButton();
        btnAlteraSenha = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        txtSenha = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Alterar Senha");

        pnlContainer.setBackground(new java.awt.Color(49, 77, 74));

        lblAlterarSenha.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblAlterarSenha.setForeground(new java.awt.Color(11, 135, 112));
        lblAlterarSenha.setText("Alterar senha");

        lblNovaSenha.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblNovaSenha.setForeground(new java.awt.Color(23, 24, 31));
        lblNovaSenha.setText("Nova senha:");

        lblConfirmeSenha.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblConfirmeSenha.setForeground(new java.awt.Color(23, 24, 31));
        lblConfirmeSenha.setText("Confirme a senha:");

        btnCancelar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnAlteraSenha.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAlteraSenha.setText("Alterar Senha");
        btnAlteraSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlteraSenhaActionPerformed(evt);
            }
        });

        txtSenha.setEditable(false);
        txtSenha.setEnabled(false);
        txtSenha.setFocusTraversalPolicyProvider(true);
        txtSenha.setRequestFocusEnabled(false);

        javax.swing.GroupLayout pnlContainerLayout = new javax.swing.GroupLayout(pnlContainer);
        pnlContainer.setLayout(pnlContainerLayout);
        pnlContainerLayout.setHorizontalGroup(
            pnlContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlContainerLayout.createSequentialGroup()
                        .addGroup(pnlContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlContainerLayout.createSequentialGroup()
                                .addComponent(lblNovaSenha)
                                .addGap(44, 44, 44)
                                .addComponent(pswNovaSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jSeparator1)
                            .addGroup(pnlContainerLayout.createSequentialGroup()
                                .addComponent(btnCancelar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnAlteraSenha)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlContainerLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(pnlContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlContainerLayout.createSequentialGroup()
                                .addComponent(lblConfirmeSenha)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pswConfirmeSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(101, 101, 101))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlContainerLayout.createSequentialGroup()
                                .addComponent(lblAlterarSenha)
                                .addGap(120, 120, 120))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlContainerLayout.createSequentialGroup()
                                .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(39, 39, 39))))))
        );
        pnlContainerLayout.setVerticalGroup(
            pnlContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlContainerLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(lblAlterarSenha)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnlContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNovaSenha)
                    .addComponent(pswNovaSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pswConfirmeSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblConfirmeSenha))
                .addGap(18, 18, 18)
                .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(pnlContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar)
                    .addComponent(btnAlteraSenha))
                .addGap(33, 33, 33))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnAlteraSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlteraSenhaActionPerformed
        // TODO add your handling code here:
        if(!emptyFields()) {
            Funcionario funcionario = TelaInicial.funcionario;
            funcionario.setCpf(txtSenha.getText());
            char[] charSenha = pswNovaSenha.getPassword();
            String senha = new String(charSenha);
            funcionario.setSenha(senha);
            
            FuncionarioDAO funcDao = new FuncionarioDAO();
            funcDao.editar(funcionario);
            JOptionPane.showMessageDialog(null, "Senha atualizada com sucesso.");
            this.dispose();

        }
    }//GEN-LAST:event_btnAlteraSenhaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaAlterarSenha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(() -> {
            TelaAlterarSenha dialog = new TelaAlterarSenha(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlteraSenha;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblAlterarSenha;
    private javax.swing.JLabel lblConfirmeSenha;
    private javax.swing.JLabel lblNovaSenha;
    private javax.swing.JPanel pnlContainer;
    private javax.swing.JPasswordField pswConfirmeSenha;
    private javax.swing.JPasswordField pswNovaSenha;
    private javax.swing.JTextField txtSenha;
    // End of variables declaration//GEN-END:variables

    private void inseriCpf() {
        txtSenha.setText(TelaInicial.funcionario.getCpf()); 
        txtSenha.setVisible(false);
    }
}
